version: '3.4'

services:
  python_services:
    stdin_open: true
    tty: true 
    platform: linux/amd64
    volumes:
        - ./work_dir:/opt/ml
        - ./program:/opt/program
    image: keras:ubuntu22_04gpu2
    build:
     context: .
     dockerfile: builds/Dockerfile_ubuntu22.04gpu2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    ports:
      - 8080:8080 