FROM ubuntu:22.04



RUN apt-get update && apt-get upgrade -y && apt-get clean
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
RUN apt-get update && apt-get upgrade -y && apt-get clean

# Python package management and basic dependencies

#RUN apt-get install -y nginx ca-certificates curl python3.8-distutils build-essential libgdal-dev python3.8-dev  #python3.9-pip
RUN apt-get install -y nginx ca-certificates curl python3 python3-pip python3-distutils build-essential libgdal-dev python3-dev  #python3.9-pip

#RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py

#RUN python3 get-pip.py

RUN apt-get install libgl1 -y
#RUN apt-get install ffmpeg libsm6 libxext6  -y

# Set a docker label to advertise multi-model support on the container

LABEL com.amazonaws.sagemaker.capabilities.multi-models=true

# Set a docker label to enable container to use SAGEMAKER_BIND_TO_PORT environment variable if present

LABEL com.amazonaws.sagemaker.capabilities.accept-bind-to-port=true

RUN ln -s /usr/bin/python3 /usr/bin/python 
# && ln -s /usr/bin/pip3 /usr/bin/pip

RUN pip install --no-cache-dir \
    awscli==1.25.90 \
    boto3==1.24.89 \
    flask==2.2.2 \
    cython==0.29.32 \
    falcon==3.1.0 \
    gunicorn==20.1.0 \
    gevent==22.8.0 \
    requests==2.28.1 \
    grpcio==1.49.1 \
    protobuf==3.19.6 \
    h5py==3.7.0 \
    opencv-contrib-python-headless==4.6.0.66 \
    pillow==9.2.0 \
    protobuf==3.19.6 \
    six==1.16.0 \
    tensorflow-cpu==2.10.0 \
    shapely==1.8.5.post1 \
    numpy==1.23.4 \
    pyparsing==2.4.7 \
    pygdal==3.4.1.10 \
    geopandas==0.11.1 \
    scipy==1.9.2 \
    click==8.1.3 \
    rasterio==1.3.2 \
    pandas==1.5.0 \
    scikit-image==0.19.3

RUN pip install --no-cache-dir \
    matplotlib==3.6.1 \
    keras==2.10.0 \
    imgaug==0.4.0 \
    ipython==8.5.0 \
    pycocotools==2.0.5 \
    sklearn

ENV PYTHONUNBUFFERED=TRUE

ENV PYTHONDONTWRITEBYTECODE=TRUE

EXPOSE 8500 8501

ENV PATH="/opt/program:${PATH}"

ENV PATH="/opt/ml/code:${PATH}"

ENV SAGEMAKER_SUBMIT_DIRECTORY /opt/ml/code
COPY program /opt/program 
WORKDIR /opt/program
